webtalk_init -webtalk_dir Z:\\zed16adc20181\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-12-27 11:51:34" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "qpheic21tktijcpji15tkfr02h" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4008 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.376 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1609036361005" -context "sdk\\\\bsp/1609036361005"
webtalk_add_data -client sdk -key hwid -value "1605100313867" -context "sdk\\\\bsp/1609036361005"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1609036361005"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\bsp/1609036361005"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1609036361005"
webtalk_add_data -client sdk -key uid -value "1609036368622" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key hwid -value "1605100313867" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key bspid -value "1609036361005" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key projSize -value "806.828125" -context "sdk\\\\application/1609036368622"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1609041094754"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1609041094754"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1609041094754"
webtalk_add_data -client sdk -key DebugCount -value "11" -context "sdk\\\\bsp/1609041094754"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1609041094754"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1609041094754"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1609041094754"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1609041094754"
webtalk_transmit -clientid 3038474454 -regid "" -xml Z:\\zed16adc20181\\webtalk\\usage_statistics_ext_sdk.xml -html Z:\\zed16adc20181\\webtalk\\usage_statistics_ext_sdk.html -wdm Z:\\zed16adc20181\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
