# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_8/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8.xci
# IP: The module: 'design_1_clk_wiz_0_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_8/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_8/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_8/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_8/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8.xci
# IP: The module: 'design_1_clk_wiz_0_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_8/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_8/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_8/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_clk_wiz_0_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
