# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/project/zedboard_16adc/zedboard_16adc.cache/wt [current_project]
set_property parent.project_path D:/project/zedboard_16adc/zedboard_16adc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo d:/project/zedboard_16adc/zedboard_16adc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files D:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_44/bd_48ac_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_51/bd_48ac_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_58/bd_48ac_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_65/bd_48ac_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_72/bd_48ac_m08s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_79/bd_48ac_m09s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_86/bd_48ac_m10s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_93/bd_48ac_m11s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_100/bd_48ac_m12s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_107/bd_48ac_m13s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_114/bd_48ac_m14s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_121/bd_48ac_m15s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_122/bd_48ac_m15arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_123/bd_48ac_m15rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_124/bd_48ac_m15awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_125/bd_48ac_m15wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_126/bd_48ac_m15bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_115/bd_48ac_m14arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_116/bd_48ac_m14rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_117/bd_48ac_m14awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_118/bd_48ac_m14wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_119/bd_48ac_m14bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_108/bd_48ac_m13arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_109/bd_48ac_m13rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_110/bd_48ac_m13awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_111/bd_48ac_m13wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_112/bd_48ac_m13bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_101/bd_48ac_m12arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_102/bd_48ac_m12rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_103/bd_48ac_m12awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_104/bd_48ac_m12wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_105/bd_48ac_m12bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_94/bd_48ac_m11arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_95/bd_48ac_m11rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_96/bd_48ac_m11awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_97/bd_48ac_m11wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_98/bd_48ac_m11bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_87/bd_48ac_m10arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_88/bd_48ac_m10rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_89/bd_48ac_m10awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_90/bd_48ac_m10wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_91/bd_48ac_m10bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_80/bd_48ac_m09arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_81/bd_48ac_m09rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_82/bd_48ac_m09awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_83/bd_48ac_m09wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_84/bd_48ac_m09bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_73/bd_48ac_m08arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_74/bd_48ac_m08rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_75/bd_48ac_m08awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_76/bd_48ac_m08wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_77/bd_48ac_m08bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_66/bd_48ac_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_67/bd_48ac_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_68/bd_48ac_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_69/bd_48ac_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_70/bd_48ac_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_59/bd_48ac_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_60/bd_48ac_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_61/bd_48ac_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_62/bd_48ac_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_63/bd_48ac_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_52/bd_48ac_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_53/bd_48ac_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_54/bd_48ac_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_55/bd_48ac_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_56/bd_48ac_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_45/bd_48ac_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_46/bd_48ac_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_47/bd_48ac_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_48/bd_48ac_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_49/bd_48ac_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/bd_48ac_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_42/bd_48ac_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_1/design_1_axi_bram_ctrl_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_2/design_1_axi_bram_ctrl_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_2/design_1_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_0_3/design_1_axi_bram_ctrl_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_1_1/design_1_axi_bram_ctrl_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_2_0/design_1_axi_bram_ctrl_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_bram_ctrl_3_0/design_1_axi_bram_ctrl_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_3/design_1_blk_mem_gen_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_1/design_1_blk_mem_gen_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_2_0/design_1_blk_mem_gen_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_3_0/design_1_blk_mem_gen_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_1/design_1_axi_gpio_1_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_1/design_1_axi_gpio_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_1/design_1_axi_gpio_1_1.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_2/design_1_axi_gpio_1_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_2/design_1_axi_gpio_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_2/design_1_axi_gpio_1_2.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_2_0/design_1_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
