# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.cache/wt [current_project]
set_property parent.project_path D:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files D:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/bd_48ac_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_42/bd_48ac_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_43/bd_48ac_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_44/bd_48ac_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_45/bd_48ac_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_47/bd_48ac_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_48/bd_48ac_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_49/bd_48ac_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_50/bd_48ac_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_51/bd_48ac_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_52/bd_48ac_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_54/bd_48ac_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_55/bd_48ac_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_56/bd_48ac_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_57/bd_48ac_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_58/bd_48ac_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_59/bd_48ac_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_8_0/design_1_axi_gpio_8_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_8_0/design_1_axi_gpio_8_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_8_0/design_1_axi_gpio_8_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_1/bd_afc3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_2/bd_afc3_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_3/bd_afc3_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_4/bd_afc3_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_5/bd_afc3_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_6/bd_afc3_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_10/bd_afc3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_11/bd_afc3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_12/bd_afc3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_16/bd_afc3_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_17/bd_afc3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_18/bd_afc3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_19/bd_afc3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_23/bd_afc3_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_24/bd_afc3_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_25/bd_afc3_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_29/bd_afc3_s03a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_30/bd_afc3_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_31/bd_afc3_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_32/bd_afc3_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_36/bd_afc3_s04a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_37/bd_afc3_sarn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_38/bd_afc3_srn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_42/bd_afc3_s05a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_43/bd_afc3_sawn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_44/bd_afc3_swn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_45/bd_afc3_sbn_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_49/bd_afc3_s06a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_50/bd_afc3_sarn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_51/bd_afc3_srn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_55/bd_afc3_s07a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_56/bd_afc3_sawn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_57/bd_afc3_swn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_58/bd_afc3_sbn_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_59/bd_afc3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_60/bd_afc3_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_61/bd_afc3_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_62/bd_afc3_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_63/bd_afc3_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_smc_0/bd_0/ip/ip_64/bd_afc3_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/design_1_axi_dma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/design_1_axi_dma_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_1_0/design_1_axi_dma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_2_0/design_1_axi_dma_2_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_system_ila_0_0/bd_0/bd_f60c_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/constrs_1/imports/new/top.xdc
set_property used_in_implementation false [get_files D:/project/zedboard_16adc/zedboard_16adc_1229_FixValue/zedboard_16adc/zedboard_16adc.srcs/constrs_1/imports/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
