# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.cache/wt [current_project]
set_property parent.project_path D:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
add_files D:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_1/design_1_proc_sys_reset_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_2/design_1_proc_sys_reset_0_2.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_4/design_1_blk_mem_gen_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_5/design_1_blk_mem_gen_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_6/design_1_blk_mem_gen_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_7/design_1_blk_mem_gen_0_7_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_8/design_1_blk_mem_gen_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_2/design_1_blk_mem_gen_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_2_1/design_1_blk_mem_gen_2_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_3_1/design_1_blk_mem_gen_3_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_3/design_1_proc_sys_reset_16M_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_3/design_1_proc_sys_reset_16M_3.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_3/design_1_proc_sys_reset_16M_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_3/design_1_proc_sys_reset_1M_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_3/design_1_proc_sys_reset_1M_3.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_7/design_1_proc_sys_reset_16M_7_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_7/design_1_proc_sys_reset_16M_7.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_7/design_1_proc_sys_reset_16M_7_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_7/design_1_proc_sys_reset_1M_7_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_7/design_1_proc_sys_reset_1M_7.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_8/design_1_proc_sys_reset_16M_8_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_8/design_1_proc_sys_reset_16M_8.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_8/design_1_proc_sys_reset_16M_8_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_8/design_1_proc_sys_reset_1M_8_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_8/design_1_proc_sys_reset_1M_8.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_9/design_1_proc_sys_reset_16M_9_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_9/design_1_proc_sys_reset_16M_9.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_9/design_1_proc_sys_reset_16M_9_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_9/design_1_proc_sys_reset_1M_9_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_9/design_1_proc_sys_reset_1M_9.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_10/design_1_proc_sys_reset_16M_10_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_10/design_1_proc_sys_reset_16M_10.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_10/design_1_proc_sys_reset_16M_10_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_10/design_1_proc_sys_reset_1M_10_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_10/design_1_proc_sys_reset_1M_10.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_11/design_1_proc_sys_reset_16M_11_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_11/design_1_proc_sys_reset_16M_11.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_11/design_1_proc_sys_reset_16M_11_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_11/design_1_proc_sys_reset_1M_11_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_11/design_1_proc_sys_reset_1M_11.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_12/design_1_proc_sys_reset_16M_12_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_12/design_1_proc_sys_reset_16M_12.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_12/design_1_proc_sys_reset_16M_12_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_12/design_1_proc_sys_reset_1M_12_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_12/design_1_proc_sys_reset_1M_12.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_8/design_1_clk_wiz_0_8_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_2_0/design_1_blk_mem_gen_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_3_0/design_1_blk_mem_gen_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_4_0/design_1_blk_mem_gen_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_5_0/design_1_blk_mem_gen_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_6_0/design_1_blk_mem_gen_6_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_7_0/design_1_blk_mem_gen_7_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_0/design_1_proc_sys_reset_16M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_0/design_1_proc_sys_reset_16M_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_0/design_1_proc_sys_reset_16M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_0/design_1_proc_sys_reset_1M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_0/design_1_proc_sys_reset_1M_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_1/design_1_proc_sys_reset_16M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_1/design_1_proc_sys_reset_16M_1.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_1/design_1_proc_sys_reset_16M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_1/design_1_proc_sys_reset_1M_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_1/design_1_proc_sys_reset_1M_1.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_2/design_1_proc_sys_reset_16M_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_2/design_1_proc_sys_reset_16M_2.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_2/design_1_proc_sys_reset_16M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_2/design_1_proc_sys_reset_1M_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_2/design_1_proc_sys_reset_1M_2.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_4/design_1_proc_sys_reset_16M_4_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_4/design_1_proc_sys_reset_16M_4.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_4/design_1_proc_sys_reset_16M_4_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_4/design_1_proc_sys_reset_1M_4_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_4/design_1_proc_sys_reset_1M_4.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_5/design_1_proc_sys_reset_16M_5_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_5/design_1_proc_sys_reset_16M_5.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_5/design_1_proc_sys_reset_16M_5_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_5/design_1_proc_sys_reset_1M_5_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_5/design_1_proc_sys_reset_1M_5.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_6/design_1_proc_sys_reset_16M_6_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_6/design_1_proc_sys_reset_16M_6.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_6/design_1_proc_sys_reset_16M_6_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_6/design_1_proc_sys_reset_1M_6_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_6/design_1_proc_sys_reset_1M_6.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_13/design_1_proc_sys_reset_16M_13_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_13/design_1_proc_sys_reset_16M_13.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_13/design_1_proc_sys_reset_16M_13_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_13/design_1_proc_sys_reset_1M_13_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_13/design_1_proc_sys_reset_1M_13.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_14/design_1_proc_sys_reset_16M_14_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_14/design_1_proc_sys_reset_16M_14.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_16M_14/design_1_proc_sys_reset_16M_14_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_14/design_1_proc_sys_reset_1M_14_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1M_14/design_1_proc_sys_reset_1M_14.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_2/design_1_blk_mem_gen_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_1_3/design_1_blk_mem_gen_1_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_10_1/design_1_blk_mem_gen_10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_11_1/design_1_blk_mem_gen_11_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_12_1/design_1_blk_mem_gen_12_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_13_1/design_1_blk_mem_gen_13_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_14_1/design_1_blk_mem_gen_14_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_15_1/design_1_blk_mem_gen_15_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_2_3/design_1_blk_mem_gen_2_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_3_3/design_1_blk_mem_gen_3_3_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_4_2/design_1_blk_mem_gen_4_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_5_2/design_1_blk_mem_gen_5_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_6_2/design_1_blk_mem_gen_6_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_7_2/design_1_blk_mem_gen_7_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_9_1/design_1_blk_mem_gen_9_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_blk_mem_gen_30_0/design_1_blk_mem_gen_30_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_1/bd_88fd_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_5/bd_88fd_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_6/bd_88fd_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_7/bd_88fd_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_8/bd_88fd_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_9/bd_88fd_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_10/bd_88fd_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/bd_0/ip/ip_11/bd_88fd_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_1_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_axis_data_fifo_0_0/design_1_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/sources_1/bd/design_1/design_1_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/constrs_1/imports/new/top.xdc
set_property used_in_implementation false [get_files D:/project/zedboard_16adc/zedboard_16adc_0104/zedboard_16adc_16/zedboard_16adc.srcs/constrs_1/imports/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top design_1_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef design_1_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
