set_property SRC_FILE_INFO {cfile:D:/zedboard_16adc_1022/zedboard_16adc/zedboard_16adc.srcs/constrs_1/imports/new/top.xdc rfile:../../../zedboard_16adc.srcs/constrs_1/imports/new/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y11 [get_ports link0_data_in]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA11 [get_ports link0_data_out]
