# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
# IP: The module: 'design_1_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_44/bd_48ac_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_51/bd_48ac_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_58/bd_48ac_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_65/bd_48ac_m07s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_72/bd_48ac_m08s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_79/bd_48ac_m09s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_86/bd_48ac_m10s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_93/bd_48ac_m11s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_100/bd_48ac_m12s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_107/bd_48ac_m13s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_114/bd_48ac_m14s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_121/bd_48ac_m15s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_127/bd_48ac_m15e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_122/bd_48ac_m15arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_123/bd_48ac_m15rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_124/bd_48ac_m15awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_125/bd_48ac_m15wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_126/bd_48ac_m15bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_120/bd_48ac_m14e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_115/bd_48ac_m14arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_116/bd_48ac_m14rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_117/bd_48ac_m14awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_118/bd_48ac_m14wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_119/bd_48ac_m14bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_113/bd_48ac_m13e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_108/bd_48ac_m13arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_109/bd_48ac_m13rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_110/bd_48ac_m13awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_111/bd_48ac_m13wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_112/bd_48ac_m13bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_106/bd_48ac_m12e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_101/bd_48ac_m12arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_102/bd_48ac_m12rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_103/bd_48ac_m12awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_104/bd_48ac_m12wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_105/bd_48ac_m12bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_99/bd_48ac_m11e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_94/bd_48ac_m11arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_95/bd_48ac_m11rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_96/bd_48ac_m11awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_97/bd_48ac_m11wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_98/bd_48ac_m11bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_92/bd_48ac_m10e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_87/bd_48ac_m10arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_88/bd_48ac_m10rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_89/bd_48ac_m10awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_90/bd_48ac_m10wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_91/bd_48ac_m10bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_85/bd_48ac_m09e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_80/bd_48ac_m09arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_81/bd_48ac_m09rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_82/bd_48ac_m09awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_83/bd_48ac_m09wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_84/bd_48ac_m09bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_78/bd_48ac_m08e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_73/bd_48ac_m08arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_74/bd_48ac_m08rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_75/bd_48ac_m08awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_76/bd_48ac_m08wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_77/bd_48ac_m08bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_71/bd_48ac_m07e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_66/bd_48ac_m07arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_67/bd_48ac_m07rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_68/bd_48ac_m07awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_69/bd_48ac_m07wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_70/bd_48ac_m07bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_64/bd_48ac_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_59/bd_48ac_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_60/bd_48ac_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_61/bd_48ac_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_62/bd_48ac_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_63/bd_48ac_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_57/bd_48ac_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_52/bd_48ac_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_53/bd_48ac_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_54/bd_48ac_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_55/bd_48ac_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_56/bd_48ac_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_50/bd_48ac_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_45/bd_48ac_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_46/bd_48ac_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_47/bd_48ac_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_48/bd_48ac_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_49/bd_48ac_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_43/bd_48ac_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/bd_48ac_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_42/bd_48ac_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m01s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m02s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m03s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_44/bd_48ac_m04s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_51/bd_48ac_m05s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_58/bd_48ac_m06s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_65/bd_48ac_m07s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_72/bd_48ac_m08s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_79/bd_48ac_m09s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_86/bd_48ac_m10s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_93/bd_48ac_m11s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_100/bd_48ac_m12s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_107/bd_48ac_m13s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_114/bd_48ac_m14s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_121/bd_48ac_m15s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_122/bd_48ac_m15arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_123/bd_48ac_m15rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_124/bd_48ac_m15awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_125/bd_48ac_m15wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_126/bd_48ac_m15bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_115/bd_48ac_m14arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_116/bd_48ac_m14rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_117/bd_48ac_m14awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_118/bd_48ac_m14wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_119/bd_48ac_m14bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_108/bd_48ac_m13arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_109/bd_48ac_m13rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_110/bd_48ac_m13awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_111/bd_48ac_m13wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_112/bd_48ac_m13bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_101/bd_48ac_m12arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_102/bd_48ac_m12rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_103/bd_48ac_m12awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_104/bd_48ac_m12wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_105/bd_48ac_m12bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_94/bd_48ac_m11arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_95/bd_48ac_m11rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_96/bd_48ac_m11awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_97/bd_48ac_m11wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_98/bd_48ac_m11bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_87/bd_48ac_m10arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_88/bd_48ac_m10rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_89/bd_48ac_m10awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_90/bd_48ac_m10wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_91/bd_48ac_m10bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_80/bd_48ac_m09arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_81/bd_48ac_m09rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_82/bd_48ac_m09awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_83/bd_48ac_m09wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_84/bd_48ac_m09bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_73/bd_48ac_m08arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_74/bd_48ac_m08rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_75/bd_48ac_m08awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_76/bd_48ac_m08wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_77/bd_48ac_m08bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_66/bd_48ac_m07arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_67/bd_48ac_m07rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_68/bd_48ac_m07awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_69/bd_48ac_m07wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_70/bd_48ac_m07bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_59/bd_48ac_m06arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_60/bd_48ac_m06rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_61/bd_48ac_m06awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_62/bd_48ac_m06wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_63/bd_48ac_m06bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_52/bd_48ac_m05arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_53/bd_48ac_m05rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_54/bd_48ac_m05awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_55/bd_48ac_m05wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_56/bd_48ac_m05bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_45/bd_48ac_m04arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_46/bd_48ac_m04rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_47/bd_48ac_m04awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_48/bd_48ac_m04wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_49/bd_48ac_m04bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m03arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m03rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m03awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/bd_48ac_m03wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_42/bd_48ac_m03bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m02arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m02rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m02awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m02wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m02bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m01arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m01rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# IP: D:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
# IP: The module: 'design_1_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/bd_48ac.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_44/bd_48ac_m04s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_51/bd_48ac_m05s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_58/bd_48ac_m06s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_65/bd_48ac_m07s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_72/bd_48ac_m08s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_79/bd_48ac_m09s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_86/bd_48ac_m10s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_93/bd_48ac_m11s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_100/bd_48ac_m12s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_107/bd_48ac_m13s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_114/bd_48ac_m14s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_121/bd_48ac_m15s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_127/bd_48ac_m15e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_122/bd_48ac_m15arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_123/bd_48ac_m15rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_124/bd_48ac_m15awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_125/bd_48ac_m15wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_126/bd_48ac_m15bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_120/bd_48ac_m14e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_115/bd_48ac_m14arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_116/bd_48ac_m14rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_117/bd_48ac_m14awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_118/bd_48ac_m14wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_119/bd_48ac_m14bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_113/bd_48ac_m13e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_108/bd_48ac_m13arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_109/bd_48ac_m13rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_110/bd_48ac_m13awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_111/bd_48ac_m13wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_112/bd_48ac_m13bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_106/bd_48ac_m12e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_101/bd_48ac_m12arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_102/bd_48ac_m12rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_103/bd_48ac_m12awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_104/bd_48ac_m12wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_105/bd_48ac_m12bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_99/bd_48ac_m11e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_94/bd_48ac_m11arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_95/bd_48ac_m11rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_96/bd_48ac_m11awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_97/bd_48ac_m11wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_98/bd_48ac_m11bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_92/bd_48ac_m10e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_87/bd_48ac_m10arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_88/bd_48ac_m10rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_89/bd_48ac_m10awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_90/bd_48ac_m10wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_91/bd_48ac_m10bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_85/bd_48ac_m09e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_80/bd_48ac_m09arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_81/bd_48ac_m09rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_82/bd_48ac_m09awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_83/bd_48ac_m09wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_84/bd_48ac_m09bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_78/bd_48ac_m08e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_73/bd_48ac_m08arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_74/bd_48ac_m08rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_75/bd_48ac_m08awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_76/bd_48ac_m08wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_77/bd_48ac_m08bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_71/bd_48ac_m07e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_66/bd_48ac_m07arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_67/bd_48ac_m07rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_68/bd_48ac_m07awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_69/bd_48ac_m07wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_70/bd_48ac_m07bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_64/bd_48ac_m06e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_59/bd_48ac_m06arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_60/bd_48ac_m06rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_61/bd_48ac_m06awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_62/bd_48ac_m06wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_63/bd_48ac_m06bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_57/bd_48ac_m05e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_52/bd_48ac_m05arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_53/bd_48ac_m05rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_54/bd_48ac_m05awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_55/bd_48ac_m05wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_56/bd_48ac_m05bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_50/bd_48ac_m04e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_45/bd_48ac_m04arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_46/bd_48ac_m04rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_47/bd_48ac_m04awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_48/bd_48ac_m04wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_49/bd_48ac_m04bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_43/bd_48ac_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/bd_48ac_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_42/bd_48ac_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_36/bd_48ac_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_29/bd_48ac_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_22/bd_48ac_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_7/bd_48ac_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_8/bd_48ac_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_9/bd_48ac_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_0/bd_48ac_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_10/bd_48ac_s00a2s_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_16/bd_48ac_m00s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_23/bd_48ac_m01s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_30/bd_48ac_m02s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_37/bd_48ac_m03s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_44/bd_48ac_m04s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_51/bd_48ac_m05s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_58/bd_48ac_m06s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_65/bd_48ac_m07s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_72/bd_48ac_m08s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_79/bd_48ac_m09s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_86/bd_48ac_m10s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_93/bd_48ac_m11s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_100/bd_48ac_m12s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_107/bd_48ac_m13s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_114/bd_48ac_m14s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_121/bd_48ac_m15s2a_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_122/bd_48ac_m15arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_123/bd_48ac_m15rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_124/bd_48ac_m15awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_125/bd_48ac_m15wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_126/bd_48ac_m15bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_115/bd_48ac_m14arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_116/bd_48ac_m14rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_117/bd_48ac_m14awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_118/bd_48ac_m14wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_119/bd_48ac_m14bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_108/bd_48ac_m13arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_109/bd_48ac_m13rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_110/bd_48ac_m13awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_111/bd_48ac_m13wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_112/bd_48ac_m13bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_101/bd_48ac_m12arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_102/bd_48ac_m12rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_103/bd_48ac_m12awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_104/bd_48ac_m12wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_105/bd_48ac_m12bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_94/bd_48ac_m11arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_95/bd_48ac_m11rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_96/bd_48ac_m11awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_97/bd_48ac_m11wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_98/bd_48ac_m11bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_87/bd_48ac_m10arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_88/bd_48ac_m10rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_89/bd_48ac_m10awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_90/bd_48ac_m10wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_91/bd_48ac_m10bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_80/bd_48ac_m09arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_81/bd_48ac_m09rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_82/bd_48ac_m09awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_83/bd_48ac_m09wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_84/bd_48ac_m09bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_73/bd_48ac_m08arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_74/bd_48ac_m08rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_75/bd_48ac_m08awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_76/bd_48ac_m08wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_77/bd_48ac_m08bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_66/bd_48ac_m07arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_67/bd_48ac_m07rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_68/bd_48ac_m07awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_69/bd_48ac_m07wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_70/bd_48ac_m07bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_59/bd_48ac_m06arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_60/bd_48ac_m06rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_61/bd_48ac_m06awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_62/bd_48ac_m06wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_63/bd_48ac_m06bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_52/bd_48ac_m05arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_53/bd_48ac_m05rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_54/bd_48ac_m05awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_55/bd_48ac_m05wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_56/bd_48ac_m05bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_45/bd_48ac_m04arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_46/bd_48ac_m04rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_47/bd_48ac_m04awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_48/bd_48ac_m04wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_49/bd_48ac_m04bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_38/bd_48ac_m03arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_39/bd_48ac_m03rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_40/bd_48ac_m03awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_41/bd_48ac_m03wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_42/bd_48ac_m03bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_31/bd_48ac_m02arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_32/bd_48ac_m02rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_33/bd_48ac_m02awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_34/bd_48ac_m02wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_35/bd_48ac_m02bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_24/bd_48ac_m01arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_25/bd_48ac_m01rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_26/bd_48ac_m01awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_27/bd_48ac_m01wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_28/bd_48ac_m01bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_17/bd_48ac_m00arn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_18/bd_48ac_m00rn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_19/bd_48ac_m00awn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_20/bd_48ac_m00wn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_21/bd_48ac_m00bn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_11/bd_48ac_sarn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_12/bd_48ac_srn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_13/bd_48ac_sawn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_14/bd_48ac_swn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_15/bd_48ac_sbn_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_2/bd_48ac_arsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_3/bd_48ac_rsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_4/bd_48ac_awsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_5/bd_48ac_wsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_6/bd_48ac_bsw_0_ooc.xdc

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/project/zedboard_16adc/zedboard_16adc.srcs/sources_1/bd/design_1/ip/design_1_smartconnect_0_0/bd_0/ip/ip_1/bd_48ac_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.
